### ISSUE TITLE
Offer to configure CORS automatically for the target bucket

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/bagger-js#24]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketCors-property

**Comment by eikeon** [comment]
This is currently not something we can do client side from a browser due to CORS restrictions. We'll need to file an enhancement request with Amazon that the top-level management endpoints set CORS headers so you can do things like enumerate buckets or set the CORS policy on a bucket
