### ISSUE TITLE
recommend policy change to support CORS

### ISSUE THREAD

**Issue by dchud** [LibraryOfCongress/bagger-js#40]
When testing this out for the first time I didn't have the `s3:GetBucketCORS` action set to Allow on my S3 policy.  I spotted the issue in the JS console when the error regarding the `Access-Control-Allow-Origin` header popped up.  Maybe you could look for these specific errors and pop up a dialog suggesting allowing the `s3:GetBucketCORS` action on bucket policies.

I suppose the same applies to `PutObject`, etc., but this one in particular is less obvious.

**Comment by acdha** [comment]
We definitely need some documentation in general (see #41). Amazon broke the S3 API awhile back for v3 signatures which was relatively easy to fix (see 2e4f695f80655cfc8b29a8910476f4f61fb87508) but as usual the Gulp and React toolchains have rotted over the last year and will require significant work to repair.

**Comment by acdha** [comment]
The help now has better instructions and the error messages are displayed in the configuration dialog. Unfortunately there's not a good way to detect a CORS failure versus another type of network error (by design) so I think this may be about as good as it gets.

**Comment by dchud** [comment]
👍
