### ISSUE TITLE
Overhaul performance metrics

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/bagger-js#8]
The current logic for tracking performance metrics getting a bit complicated and has at least one bug where React silently ignores the last update for the nested performance objects. We should review exactly what's useful to display and refactor the current logic.

**Comment by acdha** [comment]
One thing to account for in this: all of our existing stats are geared around payload data but we also upload metadata files. That leads to the upload progress bar displaying greater than 100% because we have n files + count(bag-info.txt, bagit.txt, manifest-{alg}.txt):

https://github.com/LibraryOfCongress/bagger-js/blob/bdba499dcccc8339aafcf5723c6b7d0182d60289/assets/jsx/bagger.jsx#L229

That might be solved simply by having an uploaded files counter which we use for the progress bars which tallies every successful S3 upload.

**Comment by eikeon** [comment]
These are getting overhauled in issue #31
